### ISSUE TITLE
PBSCAnalyzer stopped showing PBL files

### ISSUE THREAD

**Issue by andresmmujica** [sashazjukov/PBSCAnalyzer#1]
I'm using this tool since a few weeks without further issue, actually it's pretty good! thanks!

However I'm having this issue since a few days ago and I cannot tell what happened.   Suddenly it stopped showing the files as before and the folders are empty.  The only files I'm able to see are SQL and SRW files.

I don't really know what may have happened.   Can you give me a hand? 

v.1.0.2.1
Windows 10

![image](https://user-images.githubusercontent.com/6383804/108285161-8b1c2080-7154-11eb-9580-12cff898b1a5.png)

**Comment by sashazjukov** [comment]
check if files(*.srd, *.sru, *.srm, *.srs, *.srw) are actually exist on hard drive. Try to clear solution "Workspace->Remove all source folders", and add a source folder again. Or you can also close PBSCAnalyzer, delete the config.xml file in the PBSCAnalyzer application folder, start it and add a source folder again.

**Comment by sashazjukov** [comment]
btw, you mentioned the PBL files, but this application is designed to show the exported power builder objects. You can get this files if your solution is attached to source control like svn. So you should use that folder in the PBSCAnalyzer... Maybe you actually added a folder with PBL files instead of folder with exported objects.

**Comment by andresmmujica** [comment]
Alex you were right!  My mistake!  I was adding as source folder a local copy instead of the repo.

Thank you so much for your help!
